async function userList(){
    let data = await fetch('https://dummyjson.com/users');
    data = await data.json();
    return data.users;
}
export default async function Page() {
  let users = await userList();
  return(
     <div>
      {users.map((user, index) => (
          <h3 key={index}> Hello {user.firstName} </h3>
        ))
        }
     </div>
  )
}

export const metadata = {
  title: 'User Layout',
  description: 'Generated by create Khairul',
}